//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kino.Toolkit.Wpf {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagerResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kino.Toolkit.Wpf.DataPager.PagerResources", typeof(PagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ... 的本地化字符串。
        /// </summary>
        internal static string AutoEllipsisString {
            get {
                return ResourceManager.GetString("AutoEllipsisString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string AutomationPeerName_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("AutomationPeerName_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} 的本地化字符串。
        /// </summary>
        internal static string AutomationPeerName_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("AutomationPeerName_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        internal static string CurrentPagePrefix_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("CurrentPagePrefix_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page 的本地化字符串。
        /// </summary>
        internal static string CurrentPagePrefix_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("CurrentPagePrefix_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        internal static string CurrentPageSuffix_TotalPageCountKnown {
            get {
                return ResourceManager.GetString("CurrentPageSuffix_TotalPageCountKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentPageSuffix_TotalPageCountUnknown 的本地化字符串。
        /// </summary>
        internal static string CurrentPageSuffix_TotalPageCountUnknown {
            get {
                return ResourceManager.GetString("CurrentPageSuffix_TotalPageCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The NumericButtonPanel contains invalid children. 的本地化字符串。
        /// </summary>
        internal static string InvalidButtonPanelContent {
            get {
                return ResourceManager.GetString("InvalidButtonPanelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of argument &apos;{0}&apos; ({1}) is invalid for Enum type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumArgumentException_InvalidEnumArgument {
            get {
                return ResourceManager.GetString("InvalidEnumArgumentException_InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} time span must be strictly positive. 的本地化字符串。
        /// </summary>
        internal static string InvalidTimeSpan {
            get {
                return ResourceManager.GetString("InvalidTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The PageIndex property can only be set to -1 when the Source property is null or the PageSize property is 0. 的本地化字符串。
        /// </summary>
        internal static string PageIndexMustBeNegativeOne {
            get {
                return ResourceManager.GetString("PageIndexMustBeNegativeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cannot be set because the underlying property is read only. 的本地化字符串。
        /// </summary>
        internal static string UnderlyingPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("UnderlyingPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must be greater than or equal to {1}. 的本地化字符串。
        /// </summary>
        internal static string ValueMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
    }
}
