//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PagedCollectionViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagedCollectionViewResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kino.Toolkit.Wpf.PagedCollectionView.PagedCollectionViewResources", typeof(PagedCollectionViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CancelEdit is not supported for the current edit item. 的本地化字符串。
        /// </summary>
        internal static string CancelEditNotSupported {
            get {
                return ResourceManager.GetString("CancelEditNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Filter property cannot be set when the CanFilter property returns false. 的本地化字符串。
        /// </summary>
        internal static string CannotFilter {
            get {
                return ResourceManager.GetString("CannotFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the PageSize is not allowed during an AddNew or EditItem transaction. 的本地化字符串。
        /// </summary>
        internal static string ChangingPageSizeNotAllowedDuringAddOrEdit {
            get {
                return ResourceManager.GetString("ChangingPageSizeNotAllowedDuringAddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection was modified; enumeration operation cannot execute. 的本地化字符串。
        /// </summary>
        internal static string EnumeratorVersionChanged {
            get {
                return ResourceManager.GetString("EnumeratorVersionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index was out of range. Must be non-negative and less than the size of the collection. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of argument &apos;{0}&apos; ({1}) is invalid for Enum type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumArgument {
            get {
                return ResourceManager.GetString("InvalidEnumArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageSize cannot have a negative value. 的本地化字符串。
        /// </summary>
        internal static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot change or check the contents or current position of the PagedCollectionView while Refresh is being deferred. 的本地化字符串。
        /// </summary>
        internal static string NoCheckOrChangeWhenDeferred {
            get {
                return ResourceManager.GetString("NoCheckOrChangeWhenDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not allowed during an AddNew or EditItem transaction. 的本地化字符串。
        /// </summary>
        internal static string OperationNotAllowedDuringAddOrEdit {
            get {
                return ResourceManager.GetString("OperationNotAllowedDuringAddOrEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not allowed during a transaction started by &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string OperationNotAllowedDuringTransaction {
            get {
                return ResourceManager.GetString("OperationNotAllowedDuringTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not allowed for this view. 的本地化字符串。
        /// </summary>
        internal static string OperationNotAllowedForView {
            get {
                return ResourceManager.GetString("OperationNotAllowedForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property named &apos;{0}&apos; on type &apos;{1}&apos; cannot be read. 的本地化字符串。
        /// </summary>
        internal static string PropertyNotReadable {
            get {
                return ResourceManager.GetString("PropertyNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove/RemoveAt is not supported. 的本地化字符串。
        /// </summary>
        internal static string RemoveNotSupported {
            get {
                return ResourceManager.GetString("RemoveNotSupported", resourceCulture);
            }
        }
    }
}
